### ISSUE TITLE
Issue with library name

### ISSUE THREAD

**Issue by cmaglie** [ChicagoRobotics/CRC_Simula_Library#9]
Hi @ChicagoRobotics

we have detected that you changed the name of the library in `library.properties` from
  `CRC Simula Library`
to
  `CRC Simula Arduino IDE Library`
is that right?
We are introducing a change in the library manager that forbids this kind of changes and ignore the releases with the name that differs from the name registered in the library index.

Is it ok for you to keep the new name `CRC Simula Arduino IDE Library`? The older releases with a different name will be ignored by the library manager. In absence of an answer from you we will proceed with this proposal next week.

See also: https://github.com/arduino/Arduino/issues/7127

```
JOB 577 - 2018/01/15 15:43:12 Release CRC Simula Library:0.2.3 already loaded
JOB 577 - 2018/01/15 15:43:12 Checking out tag: 0.2.5
JOB 577 - 2018/01/15 15:43:12 Release CRC Simula Arduino IDE Library:0.2.4 has wrong library name, should be CRC Simula Library
JOB 577 - 2018/01/15 15:43:12 Checking out tag: 0.2.6
JOB 577 - 2018/01/15 15:43:12 Release CRC Simula Arduino IDE Library:0.2.6 has wrong library name, should be CRC Simula Library
JOB 577 - 2018/01/15 15:43:12 Checking out tag: 0.2.7
JOB 577 - 2018/01/15 15:43:12 Release CRC Simula Arduino IDE Library:0.2.7 has wrong library name, should be CRC Simula Library
JOB 577 - 2018/01/15 15:43:12 Checking out tag: 1.0.0
JOB 577 - 2018/01/15 15:43:12 Release CRC Simula Arduino IDE Library:1.0.0 has wrong library name, should be CRC Simula Library
```

**Comment by JamieLaing** [comment]
Hello @cmaglie, yes either version of the name is fine and no problem.  Thanks so much for checking in on this.
